version: "3"

services:
  web:
    restart: unless-stopped
    # image: whatwewant/yapi:1.2.4
    build: .
    environment:
      # SITE_HOST: example.com
      # SITE_PROTOCOL: http
      HOST: 0.0.0.0
      PORT: 8080
      DB_HOST: mongo
      DB_NAME: yapi
      # DB_USER: yapi
      # DB_PASS: yapi
      ADMIN_EMAIL: tobewhatwewant@gmail.com
      # ROOT_URL: https://mydomain.com
      USERNAME_KEY: 'result.username'
      EMAIL_KEY: 'result.email'
      SSO_ONLY: 'true'
      SSO_TOKEN_KEY: code
      SSO_AUTH_SERVER_URL: https://oauth.example.com/a2/authorize?client_id=api-docs&redirect_uri=
      SSO_AUTH_USER_URL: https://oauth.example.com/api/user?code=
      SSO_AUTH_SERVER_LOGOUT_URL: http://example.com/logout?target=
    ports:
      - 3000:8080
  
  mongo:
    restart: always
    image: mongo
