version: "3"

services:
  web:
    restart: unless-stopped
    image: whatwewant/yapi
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      DB_HOST: mongo
      DB_NAME: yapi
    ports:
      - 3000:8080
  
  mongo:
    restart: always
    image: mongo
